services:
  
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=8000
      - DATABASE_URL=""
    env_file:
      - .env
    ports:
      - 8080:8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./src:/code:rw
    

    

    




